blog/urls.py
from django.urls import re_path as url
from django.views.generic import TemplateView
from blog.views import PostList, PostDetailsView


app_name = 'blog'
urlpatterns = [
    # app urls
    url(r'^$', PostList.as_view(), name='blog_home'),
    url(r'^(?P<year>[\w-]+)/(?P<month>[\w-]+)/(?P<day>[\w-]+)/(?P<slug>[\w-]+)/$', PostDetailsView.as_view(), name='post_details'),
]

labglo_site/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import re_path as url
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
from django.contrib import admin
from django.contrib.sitemaps import views
from django.urls import reverse
from django.http import HttpResponseRedirect
from career.sitemaps import CareerSitemap
from news.sitemaps import NewsSitemap
from core.sitemaps import StaticSitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'career': CareerSitemap,
    'news': NewsSitemap,
    'static': StaticSitemap,
    'blog' : PostSitemap,
}


# def handle_error(request):
#     return HttpResponseRedirect(reverse('core:home'))


urlpatterns = [
    # Admin urls
    url(r'^nimda/', admin.site.urls),

    # Adding url of django Richtext field
    url(r'^djrichtextfield/', include('djrichtextfield.urls')),
    # CKEditor urls
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    # site urls
    url(r'^', include('core.urls')),
    url(r'^careers/', include('career.urls')),
    url(r'^news/', include('news.urls')),
    url(r'^blog/', include('blog.urls')),

    # sitemaps urls
    # url(r'^sitemap\.xml$', views.index, {'sitemaps': sitemaps}),
    url(r'^sitemap\.xml$', views.sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# handler404 = handle_error
# handler500 = handle_error

news/urls.py
from django.urls import re_path as url
from django.views.generic import TemplateView
from news.views import NewsList, news_details


app_name = 'news'
urlpatterns = [
    # app urls
    url(r'^$', NewsList.as_view(), name='home'),
    url(r'^(?P<slug>[\w-]+)/$', news_details, name='news_details'),

]

news/models.py
from __future__ import unicode_literals
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.urls import reverse


class Tag(models.Model):
    """ Model to save all tags, related to news """
    name = models.CharField(max_length=252, unique=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.name

class News(models.Model):
    """ Model to save all news """
    title = models.CharField(max_length=512)
    slug = models.SlugField(max_length=128, unique=True)
    is_active = models.BooleanField(default=True)           # To check news expired or not
    description = RichTextUploadingField()
    image_url = models.URLField(max_length=512, blank=True, null=True)
    source = models.URLField(max_length=512, blank=True, null=True)
    tag = models.ManyToManyField(Tag, related_name='tags')
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("news:news_details", kwargs={'slug':self.slug})

news/forms.py
from django import forms
from news.models import (Tag, News)


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['name',]

class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        exclude = ['created_on', 'updated_on']

news/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views import generic
from django.http import JsonResponse
from news.models import News, Tag


class NewsList(generic.ListView):
    model = News
    template_name = 'news/news_home.html'
    paginate_by = 2

    def get_queryset(self):
        tag_name = self.request.GET.get('tn', '')
        if tag_name != "":
            qset = News.objects.filter(tag__name=tag_name, is_active=True).order_by("-created_on")
        else:
            qset = News.objects.filter(is_active=True).order_by("-created_on")
        return qset

def news_details(request, slug):
    obj = get_object_or_404(News, slug=slug)
    return render(request,"news/news_details.html",
        {'news_obj': obj})

news/templates/news/news_details.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    <title>LabGlo : News Room - {{ news_obj.title }}</title>
{% endblock %}

{% block content %}

<!-- PAGE TITLE SMALL -->
<div class="page-title-cont page-title-large page-title-img grey-dark-bg pt-250" style="background-image: urls('{% static 'images/work-proc-bg' %}')">
    <div class="relative container align-left">
        <div class="row">
            <div class="col-md-8">
                <h1 class="page-title">News & Events</h1>
            </div>
      
            <div class="col-md-4">
                <div class="breadcrumbs">
                    <a href="{% url 'core:home' %}">Home</a>
                    <span>/</span>
                    <span class="bread-current"><a href="{% url 'news:home' %}">News</a></span>
                </div>
            </div>
        </div>
    </div>
</div>

    <!-- COTENT CONTAINER -->
<div class="container p-140-cont">
    <div class="row">
        <!-- CONTENT -->
        <div class="col-sm-8 blog-main-posts">
            {% if news_obj %}
                <div class="blog-post wow fadeIn pb-50">
                    <div class="post-prev-img">
                        <a href="{% url 'news:news_details' news_obj.slug %}"><img src="{{ news_obj.image_url }}" alt="{{ news_obj.title }}"></a>
                    </div>
                    <div class="post-prev-title">
                        <h3><a href="{% url 'news:news_details' news_obj.slug %}">{{ news_obj.title }}</a></h3>
                    </div>
                    <div class="post-prev-info">
                        Published on {{ news_obj.created_on }}
                    </div>
                  
                    <div class="post-prev-text">
                        <p>{{ news_obj.description|safe }}</p>
                    </div>

                    <div class="post-prev-source">
                        <p><b>Source:</b> <a href="{{ news_obj.source }}" target="_new">Click Here</a></p>
                    </div>

                    <div class="post-prev-more-cont clearfix">
                        <div class="post-prev-more left">
                            <div class="tags">
                                {% for itm in news_obj.tag.all %}
                                    <a href="{% url 'news:home' %}?tn={{ itm }}">{{ itm }}</a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            {% else %}
                <div class="col-sm-8 blog-main-posts">
                    <p>No data.</p>
                </div>
            {% endif %}
          
          <!-- DIVIDER -->
          <hr class="mt-0 mb-0">
          
          <!-- WORK NAVIGATION -->
          <!-- <div class="work-navigation clearfix">
            <a href="#" class="work-prev"><span><span class="icon icon-arrows-left"></span>&nbsp;Prev</span></a>
            <a href="{% url 'news:home' %}" class="work-all"><span>All Posts</span></a>
            <a href="#" class="work-next"><span>Next&nbsp;<span class="icon icon-arrows-right"></span></span></a>
          </div> -->
          
          <!-- DIVIDER -->
          <hr class="mt-0 mb-0">
                  
            <!-- RELATED POSTS -->
            <h4 class="blog-page-title mt-50 mb-25">RELATED POSTS</h4>
            <div class="row related-posts">
            {% if news_post %}
                {% for nws_itm in news_post %}
                    <!-- Post Item 1 -->
                    <div class="col-sm-6 col-md-4 col-lg-4 wow fadeIn pb-50" >
                        
                      <div class="post-prev-img">
                        <a href="{% url 'news:news_details' nws_itm.slug %}"><img src="{{ nws_itm.image_url}}" alt="{{ nws_itm.title }}"></a>
                      </div>
                        
                      <div class="post-prev-title">
                        <h3><a href="{% url 'news:news_details' nws_itm.slug %}">{{ nws_itm.title|safe|truncatechars:'50' }}</a></h3>
                      </div>
                        
                      <div class="post-prev-info">
                        {{ nws_itm.created_on }}
                      </div>

                    </div>
                {% endfor %}
            {% endif %}
            </div>
        </div>

        <!-- SIDEBAR -->
        <div class="col-sm-4 col-md-3 col-md-offset-1">
            <!-- WIDGET -->
            <div class="widget">
                <div class="widget-body">
                    <div class="tags">
                        <p><a href="{% url 'news:home' %}">Go Back On News Page</a></p>
                    </div>
                </div>
            </div>
            
            <!-- WIDGET -->
            <div class="widget">
                <h5 class="widget-title">Tags</h5>
                <div class="widget-body">
                    <div class="tags">
                        {% for itm in tag_list %}
                            <a href="{% url 'news:home' %}?tn={{ itm.name }}">{{ itm.name }}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

{% endblock %}

news/templates/news/news_home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    <title>LabGlo : News Room</title>
{% endblock %}

{% block content %}

<!-- PAGE TITLE SMALL -->
    <div class="page-title-cont page-title-large page-title-img grey-dark-bg pt-250" style="background-image:url(/static/images/work-proc-bg.jpg)">
        <div class="relative container align-left">
            <div class="row">
                <div class="col-md-8">
                    <h1 class="page-title">News & Events</h1>
                </div>
          
                <div class="col-md-4">
                    <div class="breadcrumbs">
                        <a href="{% url 'core:home' %}">Home</a>
                        <span>/</span>
                        <span class="bread-current">News</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- COTENT CONTAINER -->
    <div class="container p-140-cont">
        <div class="row">
            <!-- CONTENT -->
            <div class="col-sm-8 blog-main-posts">
                {% if object_list %}
                    {% for article in object_list %}
                        <!-- POST ITEM -->
                        <div class="blog-post wow fadeIn pb-50">
                            <div class="post-prev-img">
                                <a href="{% url 'news:news_details' article.slug %}"><img src="{{ article.image_url}}" alt="{{ article.title }}"></a>
                            </div>
                          
                            <div class="post-prev-title">
                                <h3><a href="{% url 'news:news_details' article.slug %}">{{ article.title }}</a></h3>
                            </div>
                          
                            <div class="post-prev-info">
                                Published on {{ article.created_on }}
                            </div>
                          
                            <div class="post-prev-text">
                                <p>{{ article.description|safe|truncatechars:"200"}}</p>
                            </div>

                            <div class="post-prev-source">
                                <p><b>Source:</b> Click <a href="{{ article.source }}" target="_new">Here</a></p>
                            </div>
                                  
                            <div class="post-prev-more-cont clearfix">
                                <div class="post-prev-more left"> <a href="{% url 'news:news_details' article.slug %}" class="blog-more">READ MORE</a> </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="blog-post wow fadeIn pb-50">
                        <p>No News presently.</p>
                    </div>
                {% endif %}

                <!-- DIVIDER -->
                <hr class="mt-0 mb-0">
                
                <!-- WORK NAVIGATION -->
                {% if is_paginated %}
                    <div class="work-navigation clearfix">
                        {% if page_obj.has_previous %}
                            <a href="?page={{ page_obj.previous_page_number }}" class="work-prev"><span><span class="icon icon-arrows-left"></span>&nbsp;Prev</span></a>
                        {% else %}
                            <a class="work-prev"><span><span class="icon icon-arrows-left"></span>&nbsp;Prev</span></a>
                        {% endif %}
                        <a href="#" class="work-all"><span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span></a>
                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}" class="work-next"><span>Next&nbsp;<span class="icon icon-arrows-right"></span></span></a>
                        {% else %}
                            <a class="work-next"><span>Next&nbsp;<span class="icon icon-arrows-right"></span></span></a>
                        {% endif %}
                    </div>
                {% endif %}
              
                <!-- DIVIDER -->
                <hr class="mt-0 mb-0">
            </div>

            <!-- SIDEBAR -->
            <div class="col-sm-4 col-md-3 col-md-offset-1">
                <!-- WIDGET -->
                <div class="widget">
                    <h5 class="widget-title">Recent News</h5>
                    <div class="widget-body">
                        <ul class="clearlist widget-posts" style="display:none;">
                        {% if news_post %}
                            {% for news in news_post %}
                                <li class="clearfix">
                                    <div class="widget-posts-descr">
                                        <a href="{% url 'news:news_details' news.slug %}" title="">{{ news.title }}</a>
                                        <div>{{ news.created_on }}</div> 
                                    </div>
                                </li>
                            {% endfor %}
                        {% endif %}
                        </ul>
                    </div>
                </div>
              
              <!-- WIDGET -->
                <div class="widget">
                    <h5 class="widget-title">Tags</h5>
                    <div class="widget-body">
                        <div class="tags">
                            {% for itm in tag_list %}
                                <a href="{% url 'news:home' %}?tn={{ itm.name }}">{{ itm.name }}</a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

{% endblock %}