blog/urls.py
from django.urls import re_path as url
from django.views.generic import TemplateView
from blog.views import PostList, PostDetailsView


app_name = 'blog'
urlpatterns = [
    # app urls
    url(r'^$', PostList.as_view(), name='blog_home'),
    url(r'^(?P<year>[\w-]+)/(?P<month>[\w-]+)/(?P<day>[\w-]+)/(?P<slug>[\w-]+)/$', PostDetailsView.as_view(), name='post_details'),
]

career/urls.py
from django.urls import re_path as url
from career.views import (JobsList, submit_resume, DriveListView, DriveDetailsView,
    drive_registration, ConfirmCandidatesList, DriveSlotCreateView, DriveTimeSlotList)

app_name = 'career'
urlpatterns = [
    url(r'^$', JobsList.as_view(), name='jobs_list'),

    url(r'^submit/resume/$', submit_resume, name='submit_resume'),

    url(r'^(?P<slug>[-\w]+)/apply/$', submit_resume, name='apply_post'),

    url(r'^drives/$', DriveListView.as_view(), name='drive_home'),

    url(r'^drive/details/(?P<slug>[\w-]+)/$', DriveDetailsView.as_view(),name='drive_details'),

    url(r'^drive/registration/(?P<slug>[\w-]+)/$', drive_registration, name='drive_registration'),

    url(r'^confirmed/candidates/$', ConfirmCandidatesList.as_view(), name='confirmed_candidated'),

    url(r'^confirm/timeslot/$', DriveSlotCreateView.as_view(), name='confirmed_timeslot'),

    url(r'^time-slots/$', DriveTimeSlotList.as_view(), name='time_slot_list'),

]

labglo_site/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import re_path as url
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
from django.contrib import admin
from django.contrib.sitemaps import views
from django.urls import reverse
from django.http import HttpResponseRedirect
from career.sitemaps import CareerSitemap
from news.sitemaps import NewsSitemap
from core.sitemaps import StaticSitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'career': CareerSitemap,
    'news': NewsSitemap,
    'static': StaticSitemap,
    'blog' : PostSitemap,
}


# def handle_error(request):
#     return HttpResponseRedirect(reverse('core:home'))


urlpatterns = [
    # Admin urls
    url(r'^nimda/', admin.site.urls),

    # Adding url of django Richtext field
    url(r'^djrichtextfield/', include('djrichtextfield.urls')),
    # CKEditor urls
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    # site urls
    url(r'^', include('core.urls')),
    url(r'^careers/', include('career.urls')),
    url(r'^news/', include('news.urls')),
    url(r'^blog/', include('blog.urls')),

    # sitemaps urls
    # url(r'^sitemap\.xml$', views.index, {'sitemaps': sitemaps}),
    url(r'^sitemap\.xml$', views.sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# handler404 = handle_error
# handler500 = handle_error

career/models.py
from __future__ import unicode_literals
from django.utils import timezone
from django.db import models
from django.urls import reverse
from django.core.validators import MinValueValidator, MaxValueValidator
from ckeditor.fields import RichTextField


class Skill(models.Model):
    """Model to list out all skills"""
    skill_name = models.CharField(max_length=252)           # Skills added by admin
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.skill_name

class JobListing(models.Model):
    """Model to save all openings in organisation"""
    is_active = models.BooleanField(default=True)           # To check is job expired or not
    job_code = models.CharField(unique=True, max_length=10)
    job_title = models.CharField(max_length=254)
    slug = models.SlugField(max_length=128, unique=True, db_index=True)
    job_description = RichTextField(blank=True, null=True)
    skills = models.ManyToManyField(Skill, related_name='required_skills')
    required_qualification = models.CharField(max_length=254, blank=True, null=True)
    is_fresher = models.BooleanField(default=False)
    min_exp = models.PositiveSmallIntegerField(blank=True, null=True)
    max_exp = models.PositiveSmallIntegerField(blank=True, null=True)
    location = models.CharField(max_length=125, blank=True, null=True)
    posting_date = models.DateTimeField(blank=True, null=True)
    closing_date = models.DateTimeField(blank=True, null=True)
    reference_link = models.URLField(max_length=512, blank=True, null=True)
    contact_email = models.EmailField(max_length=254, blank=True, null=True)
    additional_info = models.TextField(blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.job_title

    def get_absolute_url(self):
        return reverse("career:apply_post", kwargs={'slug':self.slug})

class Candidate(models.Model):
    """ Model to save the details of candidates who are submitted
    their profiles or applied for positions.
    """
    MALE = 0
    FEMALE = 1
    OTHER = 2
    GENDER_CHOICES = ( 
        (MALE, 'Male'), 
        (FEMALE, 'Female'),
        (OTHER, 'Other'),
    )

    first_name = models.CharField(max_length=252)
    last_name = models.CharField(max_length=252)
    phone = models.CharField(max_length=30)
    email = models.EmailField(max_length=254)
    gender = models.IntegerField(choices=GENDER_CHOICES, default=0)
    current_company = models.CharField(max_length=125, blank=True, null=True)
    current_location = models.CharField(max_length=125, blank=True, null=True)
    total_exp = models.PositiveSmallIntegerField(blank=True, null=True)
    relevant_exp = models.PositiveSmallIntegerField(blank=True, null=True)
    current_ctc = models.PositiveIntegerField(blank=True, null=True)
    expected_ctc = models.PositiveIntegerField(blank=True, null=True)
    resume = models.FileField(upload_to='candidate_resumes')
    notice_period = models.PositiveSmallIntegerField(blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    is_notified = models.BooleanField(default=False)

    def __unicode__(self):
        return self.first_name

    def resume_link(self):
        if self.resume:
            return "<a href='%s' target='_new'>download</a>" % (self.resume.url,)
        else:
            return "No attachment"

    resume_link.allow_tags = True

class Applicant(models.Model):
    """ To save the job post with applied candidate profile """
    candidate = models.ForeignKey(Candidate, related_name='candidate_profile', on_delete=models.CASCADE) # Pointing to candidate profile
    job_listing = models.ForeignKey(JobListing, related_name='job_listing', on_delete=models.CASCADE) # Pointing to Job position
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.candidate.first_name

class TempCandidate(Candidate):
    job_listing = models.ForeignKey(JobListing, blank=True, null=True, on_delete=models.CASCADE)
    verification_key = models.UUIDField(unique=True, db_index=True)

class Drive(models.Model):
    """ To save the placement drives details """
    title = models.CharField(max_length=512)
    slug = models.SlugField(max_length=512, unique=True, db_index=True)
    description = RichTextField(blank=True, null=True)
    from_date = models.DateTimeField(default=timezone.now, editable=True)
    to_date = models.DateTimeField(default=timezone.now, editable=True)
    location = models.CharField(max_length=128, blank=True, null=True)
    last_date_to_apply = models.DateTimeField(default=timezone.now, editable=True)
    is_active = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("career:drive_details", kwargs={'slug':self.slug})

class DriveRegistration(models.Model):
    """ To save registration details for drive """
    first_name = models.CharField(max_length=252)
    last_name = models.CharField(max_length=252)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(max_length=254)
    drive = models.ForeignKey(Drive, on_delete=models.CASCADE)
    qualification = models.CharField(max_length=256)
    course = models.CharField(max_length=256)
    percentage = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    grade = models.CharField(max_length=2, blank=True, null=True)
    college = models.CharField(max_length=512)
    university = models.CharField(max_length=512)
    location = models.CharField(max_length=512, null=True, blank=True)
    city = models.CharField(max_length=512, null=True, blank=True)
    state = models.CharField(max_length=512, null=True, blank=True)
    referred_by = models.CharField(max_length=512, null=True, blank=True)
    address = models.TextField(max_length=512, blank=True, null=True)
    is_confirmed = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('email', 'drive')
        ordering = ('created_on', 'id')

    def __unicode__(self):
        return self.first_name

    def has_confirmed_timeslot(self):
        return DriveTimeSlot.objects.filter(drive_registration=self).exists()


class DriveTimeSlot(models.Model):
    drive_registration = models.OneToOneField(DriveRegistration, on_delete=models.CASCADE)
    slot = models.DateTimeField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.drive_registration.first_name

career/forms.py
import os
from django.conf import settings
from django.template.defaultfilters import filesizeformat
from django.core.exceptions import ValidationError
from django import forms
from django.forms import ModelForm
from career.models import (Skill, JobListing, Candidate, Applicant, Drive, DriveRegistration)
from django.forms import ModelForm


class SkillForm(ModelForm):
    class Meta:
        model = Skill
        fields = ['skill_name',]

class JobListingForm(ModelForm):
    class Meta:
        model = JobListing
        exclude = ['created_on', 'updated_on']

class CandidateForm(ModelForm):
    present_openings = forms.ModelChoiceField(label='PRESENT OPENINGS', queryset=JobListing.objects.all(),
        empty_label="---Current Available Positions---", required = False)
    
    class Meta:
        model = Candidate
        fields = ['present_openings', 'first_name', 'last_name', 'phone', 'email',
        'gender','current_company', 'current_location', 'total_exp', 'relevant_exp',
        'current_ctc', 'expected_ctc', 'notice_period', 'resume']

    def __init__(self, *args, **kwargs):
        # make the request object available to the form object
        self.request = kwargs.pop('request', None)
        super(CandidateForm, self).__init__(*args, **kwargs)

    def clean_total_exp(self):
        try:
            content = self.cleaned_data['total_exp']
        except:
            content = 0
        if content > 250:
            raise forms.ValidationError("Value exceeded.")
        return content

    def clean_relevant_exp(self):
        try:
            content = self.cleaned_data['relevant_exp']
        except:
            content = 250
        if content > 10000000:
            raise forms.ValidationError("Value exceeded.")
        return content

    def clean_current_ctc(self):
        try:
            content = self.cleaned_data['current_ctc']
        except:
            content = 0
        if content > 10000000:
            raise forms.ValidationError("Value exceeded.")
        return content

    def clean_expected_ctc(self):
        try:
            content = self.cleaned_data['expected_ctc']
        except:
            content = 0
        if content > 5000000:
            raise forms.ValidationError("Value exceeded.")
        return content

    def clean_notice_period(self):
        try:
            content = self.cleaned_data['notice_period']
        except:
            content = 0
        if content > 100:
            raise forms.ValidationError("Value exceeded.")
        return content

    def clean_resume(self):
        content = self.cleaned_data['resume']
        # file_type = content.content_type.split('/')[1]
        # if file_type not in ['pdf', 'doc', 'msword', 'docx']:
        if str(content).endswith(('.pdf', '.doc', '.docx')):
            if content._size > settings.MAX_UPLOAD_SIZE:
                raise forms.ValidationError(('Please keep filesize under %s.') % (
                    filesizeformat(settings.MAX_UPLOAD_SIZE)))
        else:
            raise forms.ValidationError("Only .pdf, .doc and .docx files allowed.")
        return content

    def fields_required(self, fields):
        """Used for conditionally marking fields as required."""
        for field in fields:
            if not self.cleaned_data.get(field, ''):
                msg = forms.ValidationError("This field is required.")
                self.add_error(field, msg)

    def clean(self):
        try:
            total_exprnc = self.cleaned_data['total_exp']
        except:
            total_exprnc = 0
        if total_exprnc >= 6:
            self.fields_required(['current_company', 'relevant_exp',
                'current_ctc', 'expected_ctc','notice_period'])
        return self.cleaned_data

class ApplicantForm(ModelForm):
    class Meta:
        model = Applicant
        exclude = ['created_on', 'updated_on']

class DriveForm(ModelForm):
    class Meta:
        model = Drive
        exclude = ['created_on', 'updated_on']

class DriveRegistrationForm(ModelForm):
    class Meta:
        model = DriveRegistration
        fields = ['first_name', 'last_name', 'mobile', 'email', 'qualification',
            'course', 'percentage', 'grade', 'college', 'university', 'location',
            'city', 'state', 'referred_by', 'address' ]

    def __init__(self, *args, **kwargs):
        # make the request object available to the form object
        self.request = kwargs.pop('request', None)
        super(DriveRegistrationForm, self).__init__(*args, **kwargs)

    def clean_percentage(self):
        try:
            content = self.cleaned_data['percentage']
        except:
            content = 0
        if content > 100 :
            raise forms.ValidationError("Value exceeded.")
        elif content < 0 and content != None :
            raise forms.ValidationError("Please enter the positive value.")
        return content

    # def clean_location(self):
    #     location = self.cleaned_data['location']
    #     if location == None:
    #         raise forms.ValidationError("This field is required.")
    #     else:
    #         return location

    # def clean(self):
    #     city = self.cleaned_data['city']
    #     state = self.cleaned_data['state']
    #     if city == None or state == None:
    #         raise forms.ValidationError({'location':"Please enter correct value"})
    #     return self.cleaned_data

career/templates/career/drive_registration.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    <title>LabGlo : Drive Registration</title>
{% endblock %}


{% block content %}

<div class="page-title-cont page-title-large page-title-img grey-dark-bg pt-250" style="background-image: url(/static/images/placement-drive)">
    <div class="relative container align-left">
        <div class="row">
            <div class="col-md-8">
                <h1 class="page-title">Drive Registration</h1>
            </div>
      
            <div class="col-md-4">
                <div class="breadcrumbs">
                    <a href="{% url 'core:home' %}">Home</a>
                    <span>/</span>
                    <span class="bread-current"><a href="{% url 'career:drive_home' %}">Drives</a></span>
                </div>
            </div>
        </div>
    </div>
</div>

    <!-- COTENT CONTAINER -->
<div class="container p-140-cont">
    <div class="row">
        <div class="col-md-12" id="id_success_div">
            <div class="text-center">
                <span id="id_success_txt"></span>
            </div>
        </div>
        <div class="col-md-12" id="id_error_div">
            <div class="text-center">
                <span id="id_error_txt"></span>
            </div>
        </div>
        <div class="post-prev-title">
            <h3>{{ drive_obj.title }}</h3>
        </div>
        <div class="post-prev-info">
            Last date to apply : {{ drive_obj.last_date_to_apply }}
        </div>
        <input type="hidden" name="drive-slug" id="id_drive_slug" value="{{ drive_obj.slug }}">
        <form method="POST" action="{% url 'career:drive_registration' slug=drive_obj.slug %}" id="id_drive_registration_form" novalidate="novalidate" accept-charset="utf-8" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-md-12 mb-23">
            {% for field in form %}
                <div class="resume-field-drive" id="id_class_{{ field.name }}">
                    {{ field.label }} {{ field }}
                    <div id="{{ field.name }}" class="errors"></div>
                </div>
            {% endfor %}
            </div>
            <div class="row"></div>
            <div class="col-md-6 mb-23">
                <button type="submit" class="button medium gray" style="margin-left: 0px;">Register <img id="id_loader" src="{% static 'images/apply_loader.svg' %}" alt="Loader" width="25" /></button>
                <!-- <p>* Marked fields are mandatory.</p> -->
            </div>
        </form>
    </div>
</div>

{% endblock %}


{% block footer %}
<script type="text/javascript">

    $(document).ready(function(){
        $("input, select").addClass("form-control");
        $("#id_class_city").hide()
        $("#id_class_state").hide()
        $("#id_loader").hide()
        $("#id_success_div").hide();
        $("#id_error_div").hide();
        // $("#id_grade").attr("placeholder", "Grade/CGPA")
        $('#id_mobile, #id_percentage').keypress(function (evt) {
            var theEvent = evt || window.event;
            var key = theEvent.keyCode || theEvent.which;
            var keychar = String.fromCharCode(key);
            //alert(keychar);
            var keycheck = /[0-9]/;
            // backspace || delete || escape
            if (!(key == 8 || key == 27 || key == 46)) {
                if (!keycheck.test(keychar)) {
                    theEvent.returnValue = false; //for IE
                    if (theEvent.preventDefault) theEvent.preventDefault(); //Firefox
                }
            }
        });
    });

    var input = document.getElementById('id_location');
    var options = {
      types: ['(cities)'],
    };
    var autocomplete = new google.maps.places.Autocomplete(input, options);

    autocomplete.addListener('place_changed', function() {
        var place = autocomplete.getPlace();
        if (!place.geometry) {
            window.alert("Autocomplete's returned place contains no geometry");
            $("#id_location").val("");
            return;
        } else {
            var address = place.formatted_address.split(",");
            var city = address[0].toLowerCase();
            var state_lst = $.trim(address[1]).split(" ");
            var state = state_lst[0].toLowerCase();
            $("#id_city").val(city);
            $("#id_state").val(state);
        }
    });


    $(document).on('submit', '#id_drive_registration_form', function(event){
        event.preventDefault();
        $("#id_loader").show();
        var data = new FormData(this);
        submit_form(data);
    });

    function submit_form(data){
        var csrftoken = '{{ csrf_token }}';
        var slug = $("#id_drive_slug").val();
        $.ajax({
            url: '/careers/drive/registration/'+slug+"/",
            headers:{
                'X-CSRFToken': csrftoken,
            },
            data:data,
            cache: false,
            processData: false,
            contentType: false,
            type: 'POST',
            success: function(json){
                if (json['status']){
                    $("#id_success_txt").empty();
                    $("#id_success_txt").append(json['status']);
                    $("#id_success_div").show();
                    setTimeout(function(){
                        $("#id_success_div").hide();
                        window.location.href="/careers/drives/";
                    }, 5000)
                    $(".errors").empty();
                    $("#id_drive_registration_form")[0].reset();
                    // grecaptcha.reset();
                }else if (json['error']){
                    $("#id_error_txt").empty();
                    $("#id_error_txt").append(json['error']);
                    $("#id_error_div").show();
                    setTimeout(function(){
                        $("#id_error_div").hide();
                    }, 5000)
                    $(".errors").empty();
                }else {
                    var err_count = Object.keys(json['foo']).length;
                    $(".errors").empty();
                    $("#id_error_div").hide();
                    if(err_count>0){
                        $.each( json['foo'], function( key, value ) {
                            if (key != "__all__"){
                                $("#"+key).text(value[0]);
                            } else {
                                $("#id_error_txt").empty();
                                $("#id_error_txt").append(value);
                                $("#id_error_div").show();
                                setTimeout(function(){
                                    $("#id_error_div").hide();
                                }, 5000)
                                $(".errors").empty();
                            }
                            
                        });
                    }
                }
            $("#id_loader").hide();
            },
        });
    }
</script>

{% endblock %}

career/templates/career/drive_slot_add.html
<!DOCTYPE html>
<html>
<head>
	<title>Labglo : Add Time Slot</title>
</head>
<body>
<div class="container-fluid">
	<div class="page-header text-center">
        <h1>Add Time Slots</h1>
    </div>
	<form action="" method="POST"> {% csrf_token %}
		<p><input type="hidden" name="slot_date" value="2017-06-24"></p>
		<p>ID: <input type="text" name="field_id" required="required"></p>
		<p>Time: <input type="text" name="slot_time" required="required"></p>
		<p><button type="submit" value="Submit">Submit</button></p>
	</form>
	<div id="id_msg">
		{% if message %}
			<p>{{ message }}</p>
		{% endif %}
	</div>
</div>
</body>
</html>

career/templates/career/submit_resume.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    <title>LabGlo : Careers</title>
{% endblock %}


{% block content %}

<!-- CONTAINER -->
<div class="page-title-cont page-title-large page-title-img grey-dark-bg pt-250" style="background-image: urls('{% static 'images/career' %}'); background-position: center 90px;
background-size: 100% auto; padding-top:350px; background-repeat:no-repeat;">
  <div class="relative container align-left">
    <div class="row">
      <div class="col-md-8">
        <h1 class="page-title">CAREERS</h1>
        <div class="page-sub-title">
          Providing the skills needed to deliver results at pace</a>
        </div>
      </div>

      <div class="col-md-4">
        <div class="breadcrumbs">
          <a href="{% url 'core:home' %}">Home</a><span class="slash-divider">/</span><span class="bread-current">CAREERS</span>
        </div>
      </div>
    </div>
  </div>
  <div id="currentjob" ></div>
</div>
<div class="container p-140-cont">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="fes4-box wow fadeIn col-xs-12 col-sm-6 col-md-6" style="visibility: visible; animation-name: fadeIn;">
                <h2 class="section-title">SUBMIT <span class="bold">RESUME</span></h2>
            </div>
        </div>
    </div>


    <div class="container">
        <div class="col-md-12" id="id_success_div">
            <div class="text-center">
                <span id="id_success_txt"></span>
            </div>
        </div>
        <div class="col-md-12" id="id_error_div">
            <div class="text-center">
                <span id="id_error_txt"></span>
            </div>
        </div>
        {% if job_post %}
            <div class="col-md-12">
                <h4 style="font-weight:bold;">{{ job_post.job_title }}</h4>
                <dl class="dl-horizontal">
                    {% if job_post.job_description != "" %}
                        <dt>Description</dt> <dd>{{ job_post.job_description|safe }}</dd>
                    {% endif %}

                    {% if job_post.additional_info != "" %}
                        <dt>Additional Info</dt> <dd>{{ job_post.additional_info }}</dd>
                    {% endif %}

                    {% if job_post.required_qualification != "" %}
                        <dt>Req. Qualification</dt> <dd>{{ job_post.required_qualification }}</dd>
                    {% endif %}

                    <dt>Required Skills</dt> <dd>{% for item in job_post.skills.all %}{{ item }}, {% endfor %}</dd>

                    {% if job_post.is_fresher == True %}
                        <dt>Fresher</dt> <dd>Can apply.</dd>
                    {% endif %}

                    {% if job_post.min_exp != "" %}
                        <dt>Min. Experience</dt> <dd>{{ job_post.min_exp }} Yrs.</dd>
                    {% endif %}

                    {% if job_post.max_exp != "" %}
                        <dt>Max. Experience</dt> <dd>{{ job_post.max_exp }} Yrs.</dd>
                    {% endif %}

                    {% if job_post.location != "" %}
                        <dt>Location</dt> <dd>{{ job_post.location }}</dd>
                    {% endif %}

                    {% if job_post.posting_date != "" %}
                        <dt>Posting Date</dt> <dd>{{ job_post.posting_date|date:"d M Y" }}</dd>
                    {% endif %}

                    {% if job_post.closing_date != "" %}
                        <dt>Closing Date</dt> <dd>{{ job_post.closing_date|date:"d M Y" }}</dd>
                    {% endif %}

                    {% if job_post.contact_email != "" %}
                        <dt>Contact Email</dt> <dd>{{ job_post.contact_email }}</dd>
                    {% endif %}

                    {% if job_post.reference_link != "" %}
                        <dt>Reference Link</dt> <dd>{{ job_post.reference_link }}</dd>
                    {% endif %}
                </dl>
            </div>
            <input type="hidden" name="" value="{{ job_post.id }}" id="id_job_post">
            <div class="divider divider-center"><i class="fa fa-circle"></i></div>
        {% endif %}
        <form method="POST" id="id_resume_form" novalidate="novalidate" accept-charset="utf-8" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-md-12 mb-23">
            {% for field in form %}
                <div class="resume-field">
                    {{ field.label }} {{ field }}
                    <div id="{{ field.name }}" class="errors"></div>
                </div>
            {% endfor %}
            </div>
	        <div class="row"></div>
		    <div class="col-md-6 mb-23">
                <button type="submit" class="button medium gray" style="margin-left: 0px;">APPLY  <img id="id_loader" src="{% static 'images/apply_loader.svg' %}" alt="Loader" width="25" /></button>
                <!-- <p>* Marked fields are mandatory.</p> -->
		    </div>
        </form>
    </div>
    </div>
  </div>
</div>

</div>
{% endblock %}
{% block footer %}
<script type="text/javascript">
    $(document).ready(function(){
        $("input, select").addClass("form-control");
        $("#id_loader").hide()
        $("#id_success_div").hide();
        $("#id_error_div").hide();
        $("#id_total_exp, #id_relevant_exp").attr("placeholder", "In Months")
        $("#id_notice_period").attr("placeholder", "In Days")
        // var job_id = getUrlParameter('job_id');
        var job_id = $('#id_job_post').val();
        if (job_id != '' && job_id!=null && job_id!=undefined){
            $("#id_present_openings").val(job_id);
            // $("#id_present_openings").attr('disabled', 'disabled');
        }
        $('#id_total_exp,#id_relevant_exp,#id_current_ctc,#id_expected_ctc,#id_notice_period,#id_phone').keypress(function (evt) {
            var theEvent = evt || window.event;
            var key = theEvent.keyCode || theEvent.which;
            var keychar = String.fromCharCode(key);
            //alert(keychar);
            var keycheck = /[0-9]/;
            // backspace || delete || escape
            if (!(key == 8 || key == 27 || key == 46)) {
                if (!keycheck.test(keychar)) {
                    theEvent.returnValue = false; //for IE
                    if (theEvent.preventDefault) theEvent.preventDefault(); //Firefox
                }
            }
        });
    });
    $(document).on('submit', '#id_resume_form', function(event){
        event.preventDefault();
        var total_exp = $("#id_total_exp").val();
        $("#id_loader").show();
        var data = new FormData(this);
        submit_form(data);
    });

    function submit_form(data){
        var csrftoken = '{{ csrf_token }}';
        $.ajax({
            url: '/careers/submit/resume/',
            headers:{
                'X-CSRFToken': csrftoken,
            },
            data:data,
            cache: false,
            processData: false,
            contentType: false,
            type: 'POST',
            success: function(json){
                if (json['status']){
                    $("#id_success_txt").empty();
                    $("#id_success_txt").append(json['status']);
                    $("#id_success_div").show();
                    setTimeout(function(){
                        $("#id_success_div").hide();
                        window.location.href="/careers/";
                    }, 5000)
                    $(".errors").empty();
                    $("#id_resume_form")[0].reset();
                    // grecaptcha.reset();
                }else {
                    var err_count = Object.keys(json['foo']).length;
                    $(".errors").empty();
                    $("#id_error_div").hide();
                    if(err_count>0){
                        $.each( json['foo'], function( key, value ) {
                            $("#"+key).text(value[0]);
                        });
                    }
                }
            $("#id_loader").hide();
            },
        });
    }

    function getUrlParameter(sParam) {
        var sPageURL = decodeURIComponent(window.location.search.substring(1)),
            sURLVariables = sPageURL.split('&'),
            sParameterName,
            i;

        for (i = 0; i < sURLVariables.length; i++) {
            sParameterName = sURLVariables[i].split('=');

            if (sParameterName[0] === sParam) {
                return sParameterName[1] === undefined ? true : sParameterName[1];
            }
        }
    };

</script>
<script type="text/javascript">
    $(document).ready(function() {
        $('html, body').animate({scrollTop: $('#id_resume_form').offset().top -100 }, 'slow');
    });
</script>
{% endblock %}