blog/urls.py
from django.urls import re_path as url
from django.views.generic import TemplateView
from blog.views import PostList, PostDetailsView


app_name = 'blog'
urlpatterns = [
    # app urls
    url(r'^$', PostList.as_view(), name='blog_home'),
    url(r'^(?P<year>[\w-]+)/(?P<month>[\w-]+)/(?P<day>[\w-]+)/(?P<slug>[\w-]+)/$', PostDetailsView.as_view(), name='post_details'),
]

labglo_site/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import re_path as url
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
from django.contrib import admin
from django.contrib.sitemaps import views
from django.urls import reverse
from django.http import HttpResponseRedirect
from career.sitemaps import CareerSitemap
from news.sitemaps import NewsSitemap
from core.sitemaps import StaticSitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'career': CareerSitemap,
    'news': NewsSitemap,
    'static': StaticSitemap,
    'blog' : PostSitemap,
}


# def handle_error(request):
#     return HttpResponseRedirect(reverse('core:home'))


urlpatterns = [
    # Admin urls
    url(r'^nimda/', admin.site.urls),

    # Adding url of django Richtext field
    url(r'^djrichtextfield/', include('djrichtextfield.urls')),
    # CKEditor urls
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    # site urls
    url(r'^', include('core.urls')),
    url(r'^careers/', include('career.urls')),
    url(r'^news/', include('news.urls')),
    url(r'^blog/', include('blog.urls')),

    # sitemaps urls
    # url(r'^sitemap\.xml$', views.index, {'sitemaps': sitemaps}),
    url(r'^sitemap\.xml$', views.sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# handler404 = handle_error
# handler500 = handle_error

blog/models.py
from __future__ import unicode_literals
from datetime import date
from ckeditor.fields import RichTextField
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Tag(models.Model):
    """ Model to save all tags, related to blog """
    name = models.CharField(max_length=252, unique=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Post(models.Model):
    """ Model to save all post related to blog app
    - Tag: multiple selection available
    - Publish date: default today(editable)
    """
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=512)
    slug = models.SlugField(max_length=512, unique=True, db_index=True)
    summary = models.TextField(null=True, blank=True)
    content = RichTextField()
    is_published = models.BooleanField(default=True)
    publish_date = models.DateField(default=date.today, editable=True)
    tags = models.ManyToManyField(Tag)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        date = self.created_on
        return reverse("blog:post_details", kwargs={'slug':self.slug,
            'year': date.year, 'month': date.month, 'day': date.day})

blog/forms.py
from django import forms
from blog.models import Tag, Post


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['name',]

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ['author', 'created_on', 'updated_on']

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.views import generic
from datetime import date
from blog.models import Post, Tag


class PostList(generic.ListView):
    model = Post
    template_name = 'blog/blog_home.html'
    paginate_by = 10

    def get_queryset(self):
        tag_name = self.request.GET.get('tn', '')
        if tag_name != "":
            qset = Post.objects.filter(tags__name=tag_name,
            	is_published=True).order_by("-created_on")
        else:
            qset = Post.objects.filter(is_published=True).order_by("-created_on")
        return qset

class PostDetailsView(generic.DetailView):
    model = Post
    template_name = 'blog/post_details.html'
    context_object_name = 'post_obj'

    def get_object(self):
        obj = get_object_or_404(Post, slug=self.kwargs['slug'], is_published=True)
        return obj

blog/templates/blog/blog_home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    <title>LabGlo : Blog</title>
{% endblock %}

{% block content %}

<!-- PAGE TITLE SMALL -->
    <div class="page-title-large page-title-img grey-dark-bg pt-130" style="background-image:url(/static/images/work-proc-bg.jpg)">
        <div class="relative container align-left">
            <div class="row">
                <div class="col-md-8">
                    <h1 class="page-title">Blog</h1>
                </div>
          
                <div class="col-md-4">
                    <div class="breadcrumbs">
                        <a href="{% url 'core:home' %}">Home</a>
                        <span>/</span>
                        <span class="">Blog</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- COTENT CONTAINER -->
    <div class="container p-140-cont">
        <div class="row">
            <!-- CONTENT -->
            <div class="col-sm-8 blog-main-posts">
                {% if object_list %}
                    {% for post in object_list %}
                        <!-- POST ITEM -->
                        <div class="blog-post wow fadeIn pb-20">
                            <div class="post-prev-title">
                                <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                            </div>
                          
                            <div class="post-prev-info">
                                Published on {{ post.created_on }}
                            </div>
                          
                            <div class="post-prev-text">
                                <p>{{ post.summary|safe|truncatechars:"200"}}</p>
                            </div>

                            <!-- <div class="post-prev-more-cont clearfix">
                                <div class="post-prev-more left"> <a href="{{ post.get_absolute_url }}" class="blog-more">READ MORE</a> </div>
                            </div> -->
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="blog-post wow fadeIn pb-50">
                        <p>No blog posts presently.</p>
                    </div>
                {% endif %}

                <!-- DIVIDER -->
                <hr class="mt-0 mb-0">
                
                <!-- WORK NAVIGATION -->
                {% if is_paginated %}
                    <div class="work-navigation clearfix">
                        {% if page_obj.has_previous %}
                            <a href="?page={{ page_obj.previous_page_number }}" class="work-prev"><span><span class="icon icon-arrows-left"></span>&nbsp;Prev</span></a>
                        {% else %}
                            <a class="work-prev"><span><span class="icon icon-arrows-left"></span>&nbsp;Prev</span></a>
                        {% endif %}
                        <a href="#" class="work-all"><span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span></a>
                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}" class="work-next"><span>Next&nbsp;<span class="icon icon-arrows-right"></span></span></a>
                        {% else %}
                            <a class="work-next"><span>Next&nbsp;<span class="icon icon-arrows-right"></span></span></a>
                        {% endif %}
                    </div>
                {% endif %}
              
                <!-- DIVIDER -->
                <hr class="mt-0 mb-0">
            </div>

            <!-- SIDEBAR -->
            <div class="col-sm-4 col-md-3 col-md-offset-1">
                <!-- WIDGET -->
                <div class="widget">
                    <h5 class="widget-title">Recent posts</h5>
                    <div class="widget-body">
                        <ul class="clearlist widget-posts" style="display:none;">
                        {% if blog_posts %}
                            {% for post in blog_posts %}
                                <li class="clearfix">
                                    <div class="widget-posts-descr">
                                        <a href="{{ post.get_absolute_url }}" title="">{{ post.title }}</a>
                                        <div>{{ post.created_on }}</div> 
                                    </div>
                                </li>
                            {% endfor %}
                        {% endif %}
                        </ul>
                    </div>
                </div>
              
              <!-- WIDGET -->
                <div class="widget">
                    <h5 class="widget-title">Tags</h5>
                    <div class="widget-body">
                        <div class="tags">
                        {% if blog_tag_list %}
                            {% for itm in blog_tag_list %}
                                <a href="{% url 'blog:blog_home' %}?tn={{ itm.name }}">{{ itm.name }}</a>
                            {% endfor %}
                        {% endif %}
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

{% endblock %}

blog/templates/blog/post_details.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    <title>LabGlo : Blog - {{ post_obj.title }}</title>
    <script type="text/javascript" src="{% static 'syntaxhighlight/scripts/shCore.js' %}"></script>
    <script type="text/javascript" src="{% static 'syntaxhighlight/scripts/shBrushBash.js' %}"></script>
    <script type="text/javascript" src="{% static 'syntaxhighlight/scripts/shBrushCpp.js' %}"></script>
    <script type="text/javascript" src="{% static 'syntaxhighlight/scripts/shBrushCSharp.js' %}"></script>
    <script type="text/javascript" src="{% static 'syntaxhighlight/scripts/shBrushCss.js' %}"></script>
    <script type="text/javascript" src="{% static 'syntaxhighlight/scripts/shBrushDelphi.js' %}"></script>
    <script type="text/javascript" src="{% static 'syntaxhighlight/scripts/shBrushDiff.js' %}"></script>
    <script type="text/javascript" src="{% static 'syntaxhighlight/scripts/shBrushGroovy.js' %}"></script>
    <script type="text/javascript" src="{% static 'syntaxhighlight/scripts/shBrushJava.js' %}"></script>
    <script type="text/javascript" src="{% static 'syntaxhighlight/scripts/shBrushJScript.js' %}"></script>
    <script type="text/javascript" src="{% static 'syntaxhighlight/scripts/shBrushPhp.js' %}"></script>
    <script type="text/javascript" src="{% static 'syntaxhighlight/scripts/shBrushPlain.js' %}"></script>
    <script type="text/javascript" src="{% static 'syntaxhighlight/scripts/shBrushPython.js' %}"></script>
    <script type="text/javascript" src="{% static 'syntaxhighlight/scripts/shBrushRuby.js' %}"></script>
    <script type="text/javascript" src="{% static 'syntaxhighlight/scripts/shBrushScala.js' %}"></script>
    <script type="text/javascript" src="{% static 'syntaxhighlight/scripts/shBrushSql.js' %}"></script>
    <script type="text/javascript" src="{% static 'syntaxhighlight/scripts/shBrushVb.js' %}"></script>
    <script type="text/javascript" src="{% static 'syntaxhighlight/scripts/shBrushXml.js' %}"></script>
    <link type="text/css" rel="stylesheet" href="{% static 'syntaxhighlight/styles/shCore.css' %}"/>
    <link type="text/css" rel="stylesheet" href="{% static 'syntaxhighlight/styles/shThemeDefault.css' %}"/>
{% endblock %}

{% block content %}

<script type="text/javascript">
    SyntaxHighlighter.config.clipboardSwf = "{% static 'syntaxhighlight/scripts/clipboard.swf' %}";
    SyntaxHighlighter.all();
</script>


<!-- PAGE TITLE SMALL -->
<div class="page-title-large page-title-img grey-dark-bg pt-130" style="background-image: urls('{% static 'images/work-proc-bg' %}')">
    <div class="relative container align-left">
        <div class="row">
            <div class="col-md-8">
                <h1 class="page-title">Blog</h1>
            </div>
      
            <div class="col-md-4">
                <div class="breadcrumbs">
                    <a href="{% url 'core:home' %}">Home</a>
                    <span>/</span>
                    <span class=""><a href="{% url 'blog:blog_home' %}">Blog</a></span>
                </div>
            </div>
        </div>
    </div>
</div>

    <!-- COTENT CONTAINER -->
<div class="container p-140-cont">
    <div class="row">
        <!-- CONTENT -->
        <div class="col-sm-8 blog-main-posts">
            <!-- <p><a href="{% url 'blog:blog_home' %}">Go Back</a></p> -->
            {% if post_obj %}
                <div class="blog-post wow fadeIn pb-50">
                    <div class="post-prev-title">
                        <h3><a href="{{ post_obj.get_absolute_url }}">{{ post_obj.title }}</a></h3>
                    </div>
                    <div class="post-prev-info">
                        Published on {{ post_obj.created_on }}
                    </div>
                  
                    <div class="post-prev-text">
                        <p>{{ post_obj.summary|safe }}</p>
                    </div>

                    <div class="post-prev-text">
                        <p>{{ post_obj.content|safe }}</p>
                    </div>

                    <div class="post-prev-more-cont clearfix">
                        <div class="post-prev-more left">
                            <div class="tags">
                                {% for itm in post_obj.tags.all %}
                                    <a href="{% url 'blog:blog_home' %}?tn={{ itm }}">{{ itm }}</a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                <div id="disqus_thread"></div>
            {% else %}
                <div class="col-sm-8 blog-main-posts">
                    <p>No data.</p>
                </div>
            {% endif %}
        </div>

        <!-- SIDEBAR -->
        <div class="col-sm-4 col-md-3 col-md-offset-1">
            <!-- WIDGET -->
            <div class="widget">
                <div class="widget-body">
                    <div class="tags">
                        <p><a href="{% url 'blog:blog_home' %}">Go Back On Blog Page</a></p>
                    </div>
                </div>
            </div>
            <!-- WIDGET -->
            <div class="widget">
                <h5 class="widget-title">Tags</h5>
                <div class="widget-body">
                    <div class="tags">
                        {% if blog_tag_list %}
                            {% for itm in blog_tag_list %}
                                <a href="{% url 'blog:blog_home' %}?tn={{ itm.name }}">{{ itm.name }}</a>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<script>
    /**
    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
    /*
    var disqus_config = function () {
    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://https-labglo-com.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
</script>
<!-- <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
<script id="dsq-count-scr" src="//https-labglo-com.disqus.com/count.js" async></script>
{% endblock %}