blog/urls.py
from django.urls import re_path as url
from django.views.generic import TemplateView
from blog.views import PostList, PostDetailsView


app_name = 'blog'
urlpatterns = [
    # app urls
    url(r'^$', PostList.as_view(), name='blog_home'),
    url(r'^(?P<year>[\w-]+)/(?P<month>[\w-]+)/(?P<day>[\w-]+)/(?P<slug>[\w-]+)/$', PostDetailsView.as_view(), name='post_details'),
]

core/urls.py
from django.urls import re_path as url
from django.views.generic import TemplateView

from core.redirect import get_all_redirect_url, bola_sample
from core.views import contact, uri_encode_decode, amazon_affiliate, product_crawl

app_name = 'core'
urlpatterns = [
    # app urls
    url(r'^contact/$', contact, name='contact'),
    url(r'^product-crawl/$', product_crawl, name='product_crawl'),
    url(r'^coded/encryption/$', uri_encode_decode, name='coded_encryption'),
    url(r'^test/redirect/$', get_all_redirect_url, name='get_all_redirect_url'),
    url(r'^bola/$', bola_sample, name='bola'),
    url(r'^amazon-affiliate/$', amazon_affiliate, name='amazon-affiliate'),

    url(r'^$', TemplateView.as_view(template_name="home.html"), name='home'),
    url(r'^about-us/$', TemplateView.as_view(template_name="about_us.html"), name='about_us'),
    url(r'^services/$', TemplateView.as_view(template_name="services.html"), name='services'),
    url(r'^gallery/$', TemplateView.as_view(template_name="gallery.html"), name='gallery'),
    url(r'^url-encode-decode/$', TemplateView.as_view(template_name="url_encode_decode.html"), name='url_encode_decode'),
    url(r'^mdfaofficial/$', TemplateView.as_view(template_name="thirdpartysite.html"), name='mdfaofficial'),

]

labglo_site/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import re_path as url
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
from django.contrib import admin
from django.contrib.sitemaps import views
from django.urls import reverse
from django.http import HttpResponseRedirect
from career.sitemaps import CareerSitemap
from news.sitemaps import NewsSitemap
from core.sitemaps import StaticSitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'career': CareerSitemap,
    'news': NewsSitemap,
    'static': StaticSitemap,
    'blog' : PostSitemap,
}


# def handle_error(request):
#     return HttpResponseRedirect(reverse('core:home'))


urlpatterns = [
    # Admin urls
    url(r'^nimda/', admin.site.urls),

    # Adding url of django Richtext field
    url(r'^djrichtextfield/', include('djrichtextfield.urls')),
    # CKEditor urls
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    # site urls
    url(r'^', include('core.urls')),
    url(r'^careers/', include('career.urls')),
    url(r'^news/', include('news.urls')),
    url(r'^blog/', include('blog.urls')),

    # sitemaps urls
    # url(r'^sitemap\.xml$', views.index, {'sitemaps': sitemaps}),
    url(r'^sitemap\.xml$', views.sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# handler404 = handle_error
# handler500 = handle_error

core/forms.py
import urllib
# import urllib2
import urllib.request as urllib2
import json

from django import forms
from django.conf import settings
from django.utils.translation import gettext as _

from core.models import Lead


class LeadForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Name',
        'class': 'form-control',
        'required': 'required',
    }))
    phone = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Mobile',
        'class': 'form-control',
    }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'placeholder': 'Email',
        'class': 'form-control',
        'required': 'required',
    }))
    message = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder': 'Message',
        'class': 'form-control',
        'required': 'required',
    }))
    
    class Meta :
        model = Lead
        fields = ['name', 'phone', 'message', 'email']

    def __init__(self, *args, **kwargs):
        # make the request object available to the form object
        self.request = kwargs.pop('request', None)
        super(LeadForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = False
        self.fields['phone'].label = False
        self.fields['email'].label = False
        self.fields['message'].label = False

    def clean(self):
        super(LeadForm, self).clean()
        # test the google recaptcha
        url = "https://www.google.com/recaptcha/api/siteverify"
        values = {
            'secret': settings.RECAPTCHA_PRIVATE_KEY,
            'response': self.request.POST.get(u'g-recaptcha-response', None),
            'remoteip': self.request.META.get("REMOTE_ADDR", None),
        }
        data = urllib.urlencode(values)
        req = urllib2.Request(url, data)
        response = urllib2.urlopen(req)
        result = json.loads(response.read())

        # result["success"] will be True on a success
        if not result["success"]:
            raise forms.ValidationError(_(u'Only humans are allowed to submit this form.'))
        return self.cleaned_data


class ProductCrawlForm(forms.Form):
    """
    Form to submit request to crawl product url
    """

    url = forms.URLField(widget=forms.TextInput(attrs={
        'placeholder': 'Product URL',
        'class': 'form-control',
        'required': 'required',
    }))

    def __init__(self, *args, **kwargs):
        # make the request object available to the form object
        self.request = kwargs.pop('request', None)
        super(ProductCrawlForm, self).__init__(*args, **kwargs)
        self.fields['url'].label = False

    def clean(self):
        super(ProductCrawlForm, self).clean()
        # test the google recaptcha
        url = "https://www.google.com/recaptcha/api/siteverify"
        values = {
            'secret': settings.RECAPTCHA_PRIVATE_KEY,
            'response': self.request.POST.get(u'g-recaptcha-response', None),
            'remoteip': self.request.META.get("REMOTE_ADDR", None),
        }
        data = urllib.urlencode(values)
        req = urllib2.Request(url, data)
        response = urllib2.urlopen(req)
        result = json.loads(response.read())

        # result["success"] will be True on a success
        if not result["success"]:
            raise forms.ValidationError(_(u'Only humans are allowed to submit this form.'))
        return self.cleaned_data

templates/bola.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    <title>LabGlo : Demo</title>
{% endblock %}


{% block content %}

<div class="page-title-large page-title-img grey-dark-bg pt-250" >
    <div class="relative container align-left">
        <div class="row">
            <div class="col-md-0">
                <h1 class="page-title"> Demo </h1>
            </div>


            </div>
        </div>
    </div>
</div>

<!-- COTENT CONTAINER -->
<div class="container p-140-cont">
    <div class="row">
        <!-- CONTENT -->
        <div class="col-md-5">

                    <!--<span class="bread-current">-->
                         <form method="post" action="">
                             {% csrf_token %}
                    <input type="url"  placeholder="URL"  name="url" style="margin-right:25px; width:100%; max-width:300px;">
                    <input type="text" placeholder="COUNTRY" name="country"><br>
                             <input type="text" placeholder="Device" name="ua" ><br>
                    <input type="submit" value="Submit" class="button medium gray">
                       </form>
            {% if redirect_urls %}
            {% for url in redirect_urls%}
            <p> {{ forloop.counter }} | {{ url }} </p>
            {% endfor %}
            {% endif %}
                    <!--</span>-->
                </div>
        <!--<div class="col-sm-8 blog-main-posts" style="margin-top:30px;">-->

                <!--<div class="blog-post wow fadeIn pb-50">-->
                    <!--{% if form %}-->
                        <!--<p>Here is your url<a href=" {{ form }}" target ="_blank"> {{ form }}</a></p>-->
                    <!--{% endif %}-->
                <!--</div>-->

        <!--</div>-->
    </div>
</div>

{% endblock %}

templates/contact_us.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}
{% crispy form %}

{% block title %}
    <title>LabGlo : Contact Us</title>
{% endblock %}

{% block content %}
  <!-- PAGE TITLE -->
  <div class="page-title-cont page-title-large page-title-img grey-dark-bg pt-250" style="background-image: url(/static/images/work-proc-bg.jpg)">
    <div class="relative container align-left">
      <div class="row">

        <div class="col-md-8">
          <h1 class="page-title">CONTACT</h1>
          <div class="page-sub-title">

          </div>
        </div>

        <div class="col-md-4">
          <div class="breadcrumbs">
            <a href="{% url 'core:home' %}">Home</a><span class="slash-divider">/</span><span class="bread-current">CONTACT</span>
          </div>
        </div>

      </div>
    </div>
  </div>
   <div id="contact-link" class="page-section p-110-cont grey-light-bg">
      <div class="container">
        <div class="row">
        	<div class="col-md-4 col-sm-6">
            <div class="cis-cont">
              <div class="cis-icon">
                <div class="icon icon-basic-geolocalize-05"></div>
              </div>
              <div class="cis-text">
                <h3><span class="bold">LABGLO, INDIA</span></h3>
                <p>Module 2209, 2nd Floor, Yamuna, <br>Technopark Phase III, Sez Campus, <br>Trivandrum, <br>Kerala 695581.</p>
  	  <p> <p><img class="adjust_one" alt="Labglo India" src="{% static 'images/lab.png' %}" ></p><!--<a href="mailto:info@labglo.com"> <i class="fa fa-envelope"></i> info@labglo.com</a></p>
  	  <p><i class="fa fa-phone"></i> +91 471 4000543</p>-->
              </div>
            </div>
          </div>
          <div class="col-md-4 col-sm-6">
            <div class="cis-cont">
              <div class="cis-icon">
                <div class="icon icon-basic-geolocalize-05"></div>
              </div>
              <div class="cis-text">
                <h3><span class="bold">LABGLO, AUSTRALIA</span></h3>
                <p>  136 Albert Rd, <br>  South Melbourne,<br>  Victoria 3205</p>
  	  <p><img class="adjust" alt="Labglo Australia" src="{% static 'images/dv.png' %}" ></p><!--<i class="fa fa-envelope"></i> dvlahos@labglo.com</a></p>
  	  <p><i class="fa fa-phone"></i> +61 3 8692 5820</p>
  	  <p><i class="fa fa-phone"></i> +61 412 405 489</p>-->
              </div>
            </div>
          </div>

          <div class="col-md-4 col-sm-6">
            <div class="cis-cont">
              <div class="cis-icon">
                <div class="icon icon-basic-message-multiple"></div>
              </div>
              <div class="cis-text">
                <h3><span class="bold">ENQUIRY</span></h3>
                <p><img class="adjust_two" alt="Enquiry" src="{% static 'images/infor.png' %}" ></p>
                <!--<p><a href="mailto:info@labglo.com"><i class="fa fa-envelope"></i> info@labglo.com</a></p>
  	  <p><i class="fa fa-phone"></i> +91 471 4000543</p>-->
              </div>
            </div>
          </div>


        </div>
      </div>
    </div>

    <!-- GOOGLE MAP & CONTACT FORM -->
    <div class="page-section">
      <div class="container-fluid">
        <div class="row">

          <div class="col-md-6">
            <div class="row" style="margin-right:-10px;">
             <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3945.4938648692732!2d76.87669691478317!3d8.548416193855164!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3b05bef2dd12ae0f%3A0x359098ef5304fecc!2sTechnopark+Phase+-+III!5e0!3m2!1sen!2sin!4v1477460408005" width="100%" height="540" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
          </div>

          <div class="col-md-6">
           <div class="row" style="margin-left:-10px;">
  		        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3151.033980659444!2d144.9673381515033!3d-37.836090342996016!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6ad6680300f75e89%3A0xaeabb9f9f457a7b0!2s136+Albert+Rd%2C+South+Melbourne+VIC+3205%2C+Australia!5e0!3m2!1sen!2sin!4v1489731296606" width="100%" height="540" frameborder="0" style="border:0" allowfullscreen></iframe>
              <!-- TITLE -->


              <!-- CONTACT FORM -->

            </div>
  	</div>
          </div>

        </div>
      </div>
    </div>

    <!-- DIVIDER -->
    <hr class="mt-0 mb-0">

    <!-- CONTACT INFO SECTION 1 -->

    <!-- CLIENTS 1 & TESTIMONIALS 1 -->
    <div class="page-section pt-110-b-80-cont">
      <div class="container">
        <div class="row">
          <div class="col-md-12">

              <!-- CONTACT FORM -->
              <div class="">
                <!-- success Text -->
                <div class="col-md-12" id="id_success_div">
                  <div class="text-center">
                    <span id="id_success_txt"></span>
                  </div>
                </div>
                <form method="POST" id="contact_form" novalidate="novalidate" accept-charset="utf-8">
                  {% csrf_token %}

                  <div class="row">
                    
                    <!-- First Row -->
                    <div class="col-md-6">
                      <div class="row">

                        <div class="col-md-12 mb-30">
                          {{ form.name }}
                          <div id="name" class="errors"></div>
                        </div>

                        <div class="col-md-12 mb-23">
                          {{ form.message }}
                          <div id="message" class="errors"></div>
                        </div>

                      </div>
                    </div>
                    <!-- Second Row -->
                    <div class="col-md-6">
                      <div class="row">

                        <div class="col-md-12 mb-60">
                          {{ form.phone }}
                          <div id="phone" class="errors"></div>
                        </div>

                        <div class="col-md-12 mb-23">
                          {{ form.email }}
                          <div id="email" class="errors"></div>
                        </div>

                      </div>
                    </div>
                    <!-- reCaptch and Submit Button -->
                    <div class="col-md-6">
                      <div class="text-left">
                        <div class="g-recaptcha" data-sitekey="{{ RECAPTCHA_PUBLIC_KEY }}" data-theme="dark"></div>
                        <div id="__all__" class="errors"></div>
                      </div>
                    </div>
                    
                    <div class="col-md-6">
                      <div class="text-left">
                        <button type="submit" class="button medium gray" id="contact_submit"><img src="{% static 'images/loader.svg' %}" alt="Loader" id="id_loader" style="display:none;"> Submit</button>
                      </div>
                    </div>

                </div>

                </form>
              </div>
          </div>
        </div>
      </div>
    </div>

  <!-- NEWS LETTER -->
  <div class="divider divider-center"><i class="fa fa-circle"></i></div>

{% endblock %}

{% block footer %}
<script type="text/javascript">
    $(document).ready(function(){
        $("#id_success_div").hide();
    });
    $(document).on('submit', '#contact_form', function(event){
      event.preventDefault();
      $("#id_loader").show();
      var csrftoken = '{{ csrf_token }}';
      $.ajax({
        url: '/contact/',
        headers:{
            'X-CSRFToken': csrftoken,
        },
        data:{
          'name': $('#id_name').val(),
          'phone': $('#id_phone').val(),
          'email': $('#id_email').val(),
          'message': $('#id_message').val(),
          'g-recaptcha-response': $("#g-recaptcha-response").val(),
        },
        type: 'POST',
        success: function(json){
            if (json['status']){
                $("#id_success_txt").empty();
                $("#id_success_txt").append(json['status']);
                $("#id_success_div").show();
                setTimeout(function(){
                  $("#id_success_div").hide();
                }, 5000)
                $(".errors").empty();
                $("#contact_form")[0].reset();
                grecaptcha.reset();
            }else {
                var err_count = Object.keys(json['foo']).length;
                $(".errors").empty();
                if(err_count>0){
                    $.each( json['foo'], function( key, value ) {
                        $("#"+key).text(value);
                      // alert( key + ": " + value );
                    });
                }
            }
            $("#id_loader").hide();
        },
      });
    });

</script>
{% endblock %}

templates/product_crawl.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    <title>LabGlo : Product Crawl</title>
{% endblock %}

{% block content %}

<!-- PAGE TITLE SMALL -->
<div class="page-title-large page-title-img grey-dark-bg pt-130" style="background-image: url(/static/images/work-proc-bg.jpg)">
    <div class="relative container align-left">
        <div class="row">
            <div class="col-md-8">
                <h1 class="page-title">Product Crawl</h1>
            </div>

            <div class="col-md-4">
                <div class="breadcrumbs">
                    <a href="{% url 'core:home' %}">Home</a>
                    <span>/</span>
                    <span class="">Tool</span>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="page-section pt-110-b-80-cont">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <!-- PRODUCT CRAWL FORM -->
                <div class="">
                    <form method="POST" id="product_crawl_form" novalidate="novalidate" accept-charset="utf-8">
                        {% csrf_token %}

                        <div class="row">
                            <div class="col-md-12">
                                {{ form.url }}
                                <div id="url" class="errors"></div>
                            </div>

                            <div class="col-md-6" style="margin-bottom:20px; margin-top:15px;">
                                <!-- reCaptch and Submit Button -->
                                <div class="row">
                                <div class="col-md-12" style="margin-bottom:10px;">
                                    <div class="text-left">
                                        <div class="g-recaptcha" data-sitekey="{{ RECAPTCHA_PUBLIC_KEY }}" data-theme="light"></div>
                                        <div id="__all__" class="errors text-left" style="width:100%;padding-left:30px"></div>
                                  </div>
                                </div>
                                </div>
                                <div class="row">
                                <div class="col-md-6" style="margin-top:20px;">
                                    <div class="text-left">
                                        <button type="submit" class="button medium gray" id="product_crawl_submit"><img src="{% static 'images/loader.svg' %}" alt="Loader" id="id_loader" style="display:none;height:20px;"> Submit</button>
                                    </div>
                                </div>
                                </div>
                            </div>
                            <div class="col-md-6" style="margin-bottom:20px; margin-top:15px;">
                                <p id="image-title"style="margin-bottom:5px; margin-top:25px;"></p>
                                <img src="" id="id_image" style="max-height:300px;">
                            </div>
                        </div>
                    </form>
                </div>
                <pre id="json-renderer"></pre>
            </div>
        </div>
      </div>
</div>

<script type="text/javascript" src="{% static 'js/jquery-1.11.2.min.js' %}"></script>

<script type="text/javascript">
    $(document).ready(function(){
        $("#json-renderer").hide();
    });

    $(document).on('submit', '#product_crawl_form', function(event){
        event.preventDefault();
        $("#id_loader").show();
        var csrftoken = '{{ csrf_token }}';
        $.ajax({
            url: '/product-crawl/',
            headers:{
                'X-CSRFToken': csrftoken,
            },
            data:{
              'url': $('#id_url').val(),
              'g-recaptcha-response': $("#g-recaptcha-response").val(),
            },
            type: 'POST',
            success: function(json){
                if (json['response'] != undefined){
                    if (json['response']['title'] != undefined){
                        $('#image-title').text(json['response']['title'])
                    } else {
                        $('#image-title').empty()
                    }
                    if (json['response']['images'] != undefined) {
                        if (json['response']['images'][0] != undefined){
                            if (json['response']['images'][0]['url'] != undefined){
                                $('#id_image').attr('src', json['response']['images'][0]['url'])
                            }
                        }
                    } else {
                        $('#id_image').attr('src', '')
                    }
                    $('#json-renderer').jsonViewer(json['response']);
                    $("#json-renderer").show();
                    grecaptcha.reset();
                    $(".errors").empty();
                } else {
                    var err_count = Object.keys(json['errors']).length;
                    $(".errors").empty();
                    if(err_count>0){
                        $.each( json['errors'], function( key, value ) {
                            $("#"+key).text(value);
                        });
                    }
                }
                $("#id_loader").hide();
            },
        });
    });
</script>

{% endblock %}

templates/sample.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}
    <title>LabGlo : Amazon</title>
{% endblock %}


{% block content %}

<div class="page-title-large page-title-img grey-dark-bg pt-250" >
    <div class="relative container align-left">
        <div class="row">
            <div class="col-md-0">
                <h1 class="page-title"> Generate Amazon Affiliate URL</h1>
            </div>


            </div>
        </div>
    </div>
</div>

<!-- COTENT CONTAINER -->
<div class="container p-140-cont">
    <div class="row">
        <!-- CONTENT -->
        <div class="col-md-5">

                    <!--<span class="bread-current">-->
                         <form method="post" action="{% url 'core:amazon-affiliate'%}">
                             {% csrf_token %}
                    <input type="url"  placeholder="Enter your url here"  name="textbox-value" style="margin-right:25px; width:100%; max-width:300px;">
                    <input type="submit" value="Submit" class="button medium gray">
                       </form>
                    <!--</span>-->
                </div>
        <div class="col-sm-8 blog-main-posts" style="margin-top:30px;">

                <div class="blog-post wow fadeIn pb-50">
                    {% if form %}
                        <p>Here is your url<a href=" {{ form }}" target ="_blank"> {{ form }}</a></p>
                    {% endif %}
                </div>

        </div>
    </div>
</div>

{% endblock %}

templates/success.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}
{% crispy form %}

{% block title %}
    <title>LabGlo : Contact Us</title>
{% endblock %}

{% block content %}
  <!-- PAGE TITLE -->
  <div class="page-title-cont page-title-large page-title-img grey-dark-bg pt-250" style="background-image: url(/static/images/work-proc-bg.jpg)">
    <div class="relative container align-left">
      <div class="row">
         
        <div class="col-md-8">
          <h1 class="page-title">CONTACT</h1>
          <div class="page-sub-title">
           
          </div>
        </div>
         
        <div class="col-md-4">
          <div class="breadcrumbs">
            <a href="{% url 'core:home' %}">Home</a><span class="slash-divider">/</span><span class="bread-current">CONTACT</span>
          </div>
        </div>
        
      </div>
    </div>
  </div>
   <div id="contact-link" class="page-section p-110-cont grey-light-bg">
      <div class="container">
        <div class="row">
        	<div class="col-md-4 col-sm-6">
            <div class="cis-cont">
              <div class="cis-icon">
                <div class="icon icon-basic-geolocalize-05"></div>
              </div>
              <div class="cis-text">
                <h3><span class="bold">LABGLO, INDIA</span></h3>
                <p>Module 2209, 2nd Floor, Yamuna, <br>Technopark Phase III, Sez Campus, <br>Trivandrum, <br>Kerala 695581.</p>
  	  <p> <p><img class="adjust_one" src="{% static 'images/lab.png' %}" ></p><!--<a href="mailto:info@labglo.com"> <i class="fa fa-envelope"></i> info@labglo.com</a></p>
  	  <p><i class="fa fa-phone"></i> +91 471 4000543</p>-->
              </div>
            </div>
          </div>
          <div class="col-md-4 col-sm-6">
            <div class="cis-cont">
              <div class="cis-icon">
                <div class="icon icon-basic-geolocalize-05"></div>
              </div>
              <div class="cis-text">
                <h3><span class="bold">LABGLO, AUSTRALIA</span></h3>
                <p>  136 Albert Rd, <br>  South Melbourne,<br>  Victoria 3205</p>
  	  <p><img class="adjust" src="{% static 'images/dv.png' %}" ></p><!--<i class="fa fa-envelope"></i> dvlahos@labglo.com</a></p>
  	  <p><i class="fa fa-phone"></i> +61 3 8692 5820</p>
  	  <p><i class="fa fa-phone"></i> +61 412 405 489</p>-->
              </div>
            </div>
          </div>

          <div class="col-md-4 col-sm-6">
            <div class="cis-cont">
              <div class="cis-icon">
                <div class="icon icon-basic-message-multiple"></div>
              </div>
              <div class="cis-text">
                <h3><span class="bold">ENQUIRY</span></h3>
                <p><img class="adjust_two" src="{% static 'images/infor.png' %}" ></p>
                <!--<p><a href="mailto:info@labglo.com"><i class="fa fa-envelope"></i> info@labglo.com</a></p>
  	  <p><i class="fa fa-phone"></i> +91 471 4000543</p>-->
              </div>
            </div>
          </div>
    
          
        </div>
      </div>        
    </div>        

    <!-- GOOGLE MAP & CONTACT FORM -->
    <div class="page-section">
      <div class="container-fluid">
        <div class="row">
        
          <div class="col-md-6">
            <div class="row" style="margin-right:-10px;">
             <iframe style="pointer-events:none;" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d126274.97637385454!2d76.9154585!3d8.4903372!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3b05bef6cf0d5c0d%3A0x830e297a9cbab598!2sLabGlo!5e0!3m2!1sen!2sin!4v1445327010555" width="100%" height="540" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
          </div>

          <div class="col-md-6">
           <div class="row" style="margin-left:-10px;">
  		<iframe style="pointer-events:none;" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3151.039420936939!2d144.9673833153193!3d-37.835962979748395!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6ad6680300f75e89%3A0xaeabb9f9f457a7b0!2s136+Albert+Rd%2C+South+Melbourne+VIC+3205%2C+Australia!5e0!3m2!1sen!2sin!4v1446699913517" width="100%" height="540" frameborder="0" style="border:0" allowfullscreen></iframe>
              <!-- TITLE -->
              
                            
              <!-- CONTACT FORM -->
            
            </div>
  	</div>
          </div>
            
        </div>
      </div>
    </div>
    
    <!-- DIVIDER -->
    <hr class="mt-0 mb-0">          
    
    <!-- CONTACT INFO SECTION 1 -->
   


          <!-- CLIENTS 1 & TESTIMONIALS 1 -->
          <div class="page-section pt-110-b-80-cont">
            <div class="container">
              <div class="row">
                <div class="col-md-12">
                                  
                    <!-- CONTACT FORM -->
                    <div class="">
                      <form method="POST" action="php/contact-form.php" id="contact-form" novalidate="novalidate">
                      
                        <div class="row">
                          <p>Thank you for contacting us. Our team will get back you soon..! </p>    
                          <p>Please click <a href="{% url 'core:home' %}">HERE</a> to go back on home page.</p>
                        </div>
                                                
                      </form> 
                      <div id="contactSuccess" class="alert alert-success hidden">
                        <strong>Success!</strong> Your message has been sent to us.
                      </div>
                    
                      <div id="contactError" class="alert alert-danger hidden">
                        <strong>Error!</strong> There was an error sending your message.
                      </div>
                    </div>
                  

                </div>
                  
              </div>
            </div>
          </div>

  <!-- NEWS LETTER -->
  <div class="divider divider-center"><i class="fa fa-circle"></i></div>

{% endblock %}